spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lostfound?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: hogeonhee
    password: "0316"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
