spring:
  datasource:
    url: jdbc:mysql://localhost:3306/capstone_db?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: hogeonhee
    password: "0316"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: dev

server:
  port: 8080
