spring:
  datasource:
    url: jdbc:mysql://localhost:3306/capstone_db?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul
    username: hogeonhee
    password: "0316"

  jpa:
    hibernate:
      ddl-auto: none # 스키마는 schema.sql로 관리
    show-sql: true

  sql:
    init:
      mode: always # schema.sql, data.sql 자동 실행

  profiles:
    active: dev

server:
  port: 8080
