package com.lostfound.capstonebackend.domain.auth;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;

import java.time.LocalDateTime;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest(properties = {
        "spring.jpa.hibernate.ddl-auto=create-drop",
        "spring.jpa.properties.hibernate.hbm2ddl.auto=create-drop"
})
@ActiveProfiles("test")
class BlacklistedTokenRepositoryTest {

    @Autowired
    private BlacklistedTokenRepository blacklistedTokenRepository;

    @Autowired
    private TestEntityManager entityManager;

    @DynamicPropertySource
    static void configureProperties(DynamicPropertyRegistry registry) {
        registry.add("spring.jpa.hibernate.ddl-auto", () -> "create-drop");
        registry.add("spring.jpa.properties.hibernate.hbm2ddl.auto", () -> "create-drop");
    }

    @BeforeEach
    void setUpSchema() {
        entityManager.getEntityManager()
                .createNativeQuery("CREATE TABLE IF NOT EXISTS blacklisted_token (" +
                        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "token VARCHAR(200) NOT NULL, " +
                        "expires_at TIMESTAMP NOT NULL)"
                ).executeUpdate();
    }

    @Test
    @DisplayName("블랙리스트 토큰 저장 및 조회")
    void saveAndExistsByToken() {
        // Given
        BlacklistedToken token = BlacklistedToken.builder()
                .token("jti-1234")
                .expiresAt(LocalDateTime.now().plusHours(1))
                .build();
        blacklistedTokenRepository.save(token);

        // When & Then
        assertThat(token.getId()).isNotNull();
        assertThat(blacklistedTokenRepository.existsByToken("jti-1234")).isTrue();
        assertThat(blacklistedTokenRepository.existsByToken("jti-0000")).isFalse();
    }
}
