package com.lostfound.capstonebackend.domain.auth;

import com.lostfound.capstonebackend.domain.user.User;
import com.lostfound.capstonebackend.domain.user.UserRepository;
import com.lostfound.capstonebackend.domain.user.UserRole;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest(properties = {
        "spring.jpa.hibernate.ddl-auto=create-drop",
        "spring.jpa.properties.hibernate.hbm2ddl.auto=create-drop"
})
@ActiveProfiles("test")
class UserRepositoryTest {

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private TestEntityManager entityManager;

    @DynamicPropertySource
    static void configureProperties(DynamicPropertyRegistry registry) {
        registry.add("spring.jpa.hibernate.ddl-auto", () -> "create-drop");
        registry.add("spring.jpa.properties.hibernate.hbm2ddl.auto", () -> "create-drop");
    }

    @BeforeEach
    void setUpSchema() {
        entityManager.getEntityManager()
                .createNativeQuery("CREATE TABLE IF NOT EXISTS users (" +
                        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "email VARCHAR(255) NOT NULL, " +
                        "password VARCHAR(255) NOT NULL, " +
                        "name VARCHAR(100) NOT NULL, " +
                        "phone VARCHAR(20), " +
                        "role VARCHAR(20) NOT NULL, " +
                        "created_at TIMESTAMP, " +
                        "updated_at TIMESTAMP)"
                ).executeUpdate();
    }

    @Test
    @DisplayName("이메일로 사용자 조회")
    void findByEmail() {
        // Given
        User user = persistUser("find@example.com", "홍길동");

        // When
        var result = userRepository.findByEmail("find@example.com");

        // Then
        assertThat(result).isPresent();
        assertThat(result.get().getName()).isEqualTo("홍길동");
    }

    @Test
    @DisplayName("이메일 존재 여부 확인")
    void existsByEmail() {
        // Given
        persistUser("exists@example.com", "아무개");

        // When & Then
        assertThat(userRepository.existsByEmail("exists@example.com")).isTrue();
        assertThat(userRepository.existsByEmail("absent@example.com")).isFalse();
    }

    @Test
    @DisplayName("ID와 이메일로 사용자 조회")
    void findByIdAndEmail() {
        // Given
        User user = persistUser("combo@example.com", "콤보");

        // When
        var result = userRepository.findByIdAndEmail(user.getId(), "combo@example.com");

        // Then
        assertThat(result).isPresent();
        assertThat(result.get().getEmail()).isEqualTo("combo@example.com");
    }

    @Test
    @DisplayName("이름 부분 일치 검색")
    void findByNameContaining() {
        // Given
        persistUser("alpha@example.com", "김철수");
        persistUser("beta@example.com", "김영희");
        persistUser("gamma@example.com", "이몽룡");

        // When
        List<User> results = userRepository.findByNameContaining("김");

        // Then
        assertThat(results).hasSize(2);
        assertThat(results).extracting(User::getEmail).contains("alpha@example.com", "beta@example.com");
    }

    private User persistUser(String email, String name) {
        User user = User.builder()
                .username(email.split("@")[0]) // 이메일 앞부분을 username으로 사용
                .email(email)
                .password("encoded")
                .name(name)
                .phone("010-0000-0000")
                .role(UserRole.USER)
                .build();
        return entityManager.persistFlushFind(user);
    }
}
