package com.lostfound.capstonebackend.domain.lostitem;

import com.lostfound.capstonebackend.domain.user.User;
import com.lostfound.capstonebackend.domain.user.UserRole;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest(properties = {
        "spring.jpa.hibernate.ddl-auto=create-drop",
        "spring.jpa.properties.hibernate.hbm2ddl.auto=create-drop"
})
@ActiveProfiles("test")
class LostItemRepositoryTest {

    @Autowired
    private LostItemRepository lostItemRepository;

    @Autowired
    private TestEntityManager entityManager;

    @DynamicPropertySource
    static void configureProperties(DynamicPropertyRegistry registry) {
        registry.add("spring.jpa.hibernate.ddl-auto", () -> "create-drop");
        registry.add("spring.jpa.properties.hibernate.hbm2ddl.auto", () -> "create-drop");
    }

    @BeforeEach
    void setUpSchema() {
        entityManager.getEntityManager()
                .createNativeQuery("CREATE TABLE IF NOT EXISTS users (" +
                        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "email VARCHAR(255) NOT NULL, " +
                        "password VARCHAR(255) NOT NULL, " +
                        "name VARCHAR(100) NOT NULL, " +
                        "phone VARCHAR(20), " +
                        "role VARCHAR(20) NOT NULL, " +
                        "created_at TIMESTAMP, " +
                        "updated_at TIMESTAMP)"
                ).executeUpdate();

        entityManager.getEntityManager()
                .createNativeQuery("CREATE TABLE IF NOT EXISTS lost_item (" +
                        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "title VARCHAR(100) NOT NULL, " +
                        "description TEXT, " +
                        "category VARCHAR(50), " +
                        "location VARCHAR(200), " +
                        "found_date DATE, " +
                        "status VARCHAR(20), " +
                        "external_id VARCHAR(100), " +
                        "view_count INT, " +
                        "received_date TIMESTAMP, " +
                        "datasource VARCHAR(20), " +
                        "color VARCHAR(50), " +
                        "storage_location VARCHAR(200), " +
                        "image_path VARCHAR(255), " +
                        "user_id BIGINT, " +
                        "created_at TIMESTAMP, " +
                        "updated_at TIMESTAMP)"
                ).executeUpdate();
    }

    @Test
    @DisplayName("키워드 검색")
    void findByKeyword() {
        // Given
        persistItem("지갑을 주웠습니다", "설명", "서울역", "지갑", LostItem.Status.FOUND);
        persistItem("우산", "설명", "강남", "우산", LostItem.Status.FOUND);

        // When
        var page = lostItemRepository.findByKeyword("지갑", PageRequest.of(0, 10));

        // Then
        assertThat(page.getContent()).hasSize(1);
        assertThat(page.getContent().get(0).getTitle()).contains("지갑");
    }

    @Test
    @DisplayName("복합 검색")
    void findByComplexSearch() {
        // Given
        persistItem("노트북", "맥북 프로", "서울", "전자기기", LostItem.Status.FOUND, LocalDate.of(2024, 1, 1));
        persistItem("노트", "공책", "서울", "문구", LostItem.Status.FOUND, LocalDate.of(2024, 1, 1));

        // When
        var page = lostItemRepository.findByComplexSearch("노트", "전자기기", LostItem.Status.FOUND, null,
                LocalDate.of(2023, 12, 1), LocalDate.of(2024, 12, 31), PageRequest.of(0, 10));

        // Then
        assertThat(page.getContent()).hasSize(1);
        assertThat(page.getContent().get(0).getCategory()).isEqualTo("전자기기");
    }

    @Test
    @DisplayName("지역 검색")
    void findByRegion() {
        // Given
        persistItem("핸드폰", "설명", "서울역 대합실", "전자기기", LostItem.Status.FOUND);
        persistItem("가방", "설명", "부산", "가방", LostItem.Status.FOUND);

        // When
        var page = lostItemRepository.findByRegion("서울", PageRequest.of(0, 10));

        // Then
        assertThat(page.getContent()).hasSize(1);
        assertThat(page.getContent().get(0).getLocation()).contains("서울");
    }

    @Test
    @DisplayName("상태별 최근 분실물")
    void findRecentByStatus() {
        // Given
        persistItem("지갑", "설명", "서울", "지갑", LostItem.Status.FOUND);
        persistItem("휴대폰", "설명", "서울", "전자", LostItem.Status.FOUND);

        Pageable pageable = PageRequest.of(0, 5);

        // When
        List<LostItem> results = lostItemRepository.findRecentByStatus(LostItem.Status.FOUND, pageable);

        // Then
        assertThat(results).hasSize(2);
        assertThat(results.get(0).getCreatedAt()).isAfterOrEqualTo(results.get(1).getCreatedAt());
    }

    private void persistItem(String title, String description, String location, String category, LostItem.Status status) {
        persistItem(title, description, location, category, status, LocalDate.now());
    }

    private void persistItem(String title, String description, String location, String category, LostItem.Status status, LocalDate foundDate) {
        User owner = User.builder()
                .email(title + "@example.com")
                .password("encoded")
                .name("사용자")
                .phone("010-0000-0000")
                .role(UserRole.USER)
                .build();
        entityManager.persist(owner);

        LostItem item = LostItem.builder()
                .title(title)
                .description(description)
                .location(location)
                .category(category)
                .foundDate(foundDate)
                .status(status)
                .dataSource(LostItem.DataSource.USER)
                .owner(owner)
                .build();
        entityManager.persist(item);
        entityManager.flush();
        entityManager.clear();
    }
}
